enable save result to file
silicon-heaven/shvspy pull request #42
Opened 2024-01-19 16:31 UTC by MartinKT

2024-01-19 16:34 UTC, syyyr requested changes

2024-01-19 16:34 UTC, syyyr commented on shvspy/src/texteditdialog.cpp
> +		f.close();
Není potřeba

2024-01-19 16:34 UTC, syyyr commented on shvspy/src/mainwindow.cpp
> +		QByteArray data = QByteArray::fromRawData(std::get<0>(rv_data), std::get<1>(rv_data));
může být `auto data`

2024-01-19 17:50 UTC, MartinKT commented on shvspy/src/texteditdialog.cpp
> +		f.close();
Opraveno

2024-01-19 17:50 UTC, MartinKT commented on shvspy/src/mainwindow.cpp
> +		QByteArray data = QByteArray::fromRawData(std::get<0>(rv_data), std::get<1>(rv_data));
Opraveno

2024-01-19 17:53 UTC, syyyr approved these changes

2024-01-19 17:53 UTC, syyyr commented
Díky za opravy

2024-01-19 17:53 UTC, syyyr commented
Ty faily na clazy clang-tidy ignorujte teď, je to bug

2024-01-21 18:44 UTC, fvacek commented on shvspy/src/mainwindow.cpp
> +		auto rv_data = rv.asData();
```c++
		auto [blob, size] = rv.asData();
		auto data = QByteArray::fromRawData(blob, size);
```
is more readable

2024-01-22 11:32 UTC, MartinKT commented on shvspy/src/mainwindow.cpp
> +		auto rv_data = rv.asData();
Opraveno, super tip.

2024-02-02 20:01 UTC, merged